# Generated by Django 2.2.6 on 2019-12-02 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='博客标题')),
                ('author', models.CharField(max_length=20, verbose_name='发表作者')),
                ('content', models.TextField(max_length=255, verbose_name='发表内容')),
                ('pbtime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '博客表',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '博客标签表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='称呼')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('content', models.CharField(max_length=240, verbose_name='内容')),
                ('pbtime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boke.Blog', verbose_name='博客')),
            ],
            options={
                'verbose_name': '评论表',
            },
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('level', models.IntegerField(verbose_name='分类级别')),
                ('uper_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sonm', to='boke.BlogType', verbose_name='上级编号')),
            ],
            options={
                'verbose_name': '博客分类表',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blogtag',
            field=models.ManyToManyField(to='boke.BlogTag', verbose_name='博客标签'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boke.BlogType', verbose_name='博客类别'),
        ),
    ]
